# Matemáticas para la IA (02MIAR)

**Ejercicios evaluables. Máster Universitario en Inteligencia Artificial (VIU)**

### Integrantes del grupo (Grupo 20)

| | Nombre y apellidos |
|---|---|
| 1 | Ana María Cochiorca Dragomir |
| 2 | Ricardo Germes Serrano |
| 3 | Carlos Jurado Zalaya |
| 4 | Jorge Ramilo Plata |

---

Plantilla de trabajo del entregable. Cada apartado tiene su celda de texto y su celda de código para ir rellenando. El notebook está pensado para ejecutarse de arriba abajo.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import time
%matplotlib inline

np.random.seed(42)

## Ejercicio 1. Determinante y coste computacional

## 1a. Implementa una función `determinante_recurivo` 
La función debe calcular el determinante de una matriz cuadrada usando la expansión de Laplace.

**Pasos:**

1. Si la matriz es $1\times1$, devolver su único elemento.
2. Si la matriz es $2\times2$, usar directamente $ad-bc$.
3. Para matrices mayores, recorrer la primera fila.
4. Para cada elemento, construir la submatriz eliminando la fila 0 y la columna correspondiente.
5. Acumular el cofactor correspondiente.

In [15]:
def determinante_recursivo(A):
    """
    Calcula el determinante de una matriz cuadrada A usando
    la definición recursiva de Laplece por la pimrera fila.
    """
    n = len(A)

    # Caso base 1x1:
    if n == 1:
        return A[0][0]

    # Caso base 2x2:
    if n == 2:
        return A[0][0] * A[1][1] - A[0][1] * A[1][0]

    det = 0.0
    for j in range(n):
        submatriz = [fila[:j] + fila[j+1:] for fila in A[1:]]
        cofactor = ((-1) ** j) * A[0][J] * determinante_recursivo(submatriz)
        det += cofactor

    return det

# Prueba:
A = [[1, 2], [3, 4]]
print("det(A) =", determinante_recursivo(A))

det(A) = -2


## 1b. Determinante de una matriz triangular

Sí. Si $A$ es una matriz cuadrada triangular, ya sea superior o inferior, su determinante se calcula multiplicando los elementos de la diagonal principal:

$$
\det(A)=a_{11}a_{22}\cdots a_{nn}=\prod_{i=1}^{n}a_{ii}.
$$

## JUSTIFICACIÓN.

**PRIMERO:**
Partimos de una matriz cuadrada $n \times n$, donde: $$ A \in \mathbb{R}^{n \times n}$$ 
Esto signfica que $A$ tiene $n$ filas y $n$ columnas.


**SEGUNDO:**
En una matriz triangular superior, todos los elementos por debajo de la diagonal principal son cero. Por ejemplo:

$$
A=
\begin{pmatrix}
a_{11} & a_{12} & a_{13} & \cdots & a_{1n} \\
0 & a_{22} & a_{23} & \cdots & a_{2n} \\
0 & 0 & a_{33} & \cdots & a_{3n} \\
\vdots & \vdots & \vdots & \ddots & \vdots \\
0 & 0 & 0 & \cdots & a_{nn}
\end{pmatrix}
$$

Los elementos de la diagonal principal son:

$$
a_{11}, a_{22}, a_{33}, \ldots, a_{nn}.
$$


**TERCERO:**
Si usamos la definición recursiva del determinate, según la definición de Laplace, el determinante de una matriz cuadrada se puede calcular como:
$$
\det(A)=\sum_{j=1}^{n}(-1)^{1+j}a_{1j}\det(A_{1j}),
$$
Donde: $A_{1j}$ es la submatriz que se obtiene al eliminar la fila 1 y la columna $j$.


**CUARTO:**
Si la matriz es triangular, al ir calculando determinantes de submatrices, estas submatrices mantienen la estructura triangular, es decir: como la matriz tiene ceros a un lado de la diagonal, al calcular su determinante solo van quedando los números de la diagonal principal. Por eso no hace falta hacer un cálculo largo, basta con multiplicar esos números.


**QUINTO:**
Justificación con una matriz triangular superior.

Partimos de que tenemos una matriz: 
$$
A=
\begin{pmatrix}
a_{11} & * & * & \cdots & * \\
0 & a_{22} & * & \cdots & * \\
0 & 0 & a_{33} & \cdots & * \\
\vdots & \vdots & \vdots & \ddots & \vdots \\
0 & 0 & 0 & \cdots & a_{nn}
\end{pmatrix}
$$

Al aplicar la expansión de Laplace, el cálculo se reduce a:

$$
\det(A)=a_{11}\det(A_{11}).
$$
La submatriz $A_{11}$ también es triangular superior:

$$
A_{11}=
\begin{pmatrix}
a_{22} & * & \cdots & * \\
0 & a_{33} & \cdots & * \\
\vdots & \vdots & \ddots & \vdots \\
0 & 0 & \cdots & a_{nn}
\end{pmatrix}
$$

Por lo tanto:

$$
\det(A_{11})=a_{22}\det(A_{22}).
$$

Sustituyendo:

$$
\det(A)=a_{11}a_{22}\det(A_{22}).
$$

Repitiendo el mismo razonamiento:

$$
\det(A)=a_{11}a_{22}a_{33}\cdots a_{nn}.
$$


**SEXTO:**
Justificación con una matriz triangular inferior.

En este caso la matriz triángular inferior tiene ceros por encima de la diagonal principal, como por ejemplo:

$$
A=
\begin{pmatrix}
a_{11} & 0 & 0 & \cdots & 0 \\
a_{21} & a_{22} & 0 & \cdots & 0 \\
a_{31} & a_{32} & a_{33} & \cdots & 0 \\
\vdots & \vdots & \vdots & \ddots & \vdots \\
a_{n1} & a_{n2} & a_{n3} & \cdots & a_{nn}
\end{pmatrix}
$$

como en el caso de la matriz triangular superior al hacerse del mismo modemos, también obtenemos que:

$$
\det(A)=a_{11}a_{22}\cdots a_{nn}.
$$


### Ejercicios de Ejemplo



**1) Ejercicio con matriz triángulo Superior**

Consideremos la matriz triangular superior:

$$
A=
\begin{pmatrix}
2 & 5 & -1 \\
0 & 3 & 4 \\
0 & 0 & -2
\end{pmatrix}
$$

Como es triangular superior:

$$
\det(A)=2\cdot3\cdot(-2)=-12.
$$

In [28]:
import numpy as np

A = np.array([
    [2, 5, -1],
    [0, 3, 4],
    [0, 0, -2]
], dtype=float)
             
# Determinante directo por producto de la diagonal
det_diagonal = np.prod(np.diag(A))

# Comprobación con NumPy
det_numpy = np.linalg.det(A)

print("Matriz A:")
print(A)
print("\nProducto de la diagonal:", det_diagonal)
print("Determinante con numpy.linalg.det", det_numpy)

Matriz A:
[[ 2.  5. -1.]
 [ 0.  3.  4.]
 [ 0.  0. -2.]]

Producto de la diagonal: -12.0
Determinante con numpy.linalg.det -12.0


**2) Ejercicio con matriz triángulo Inferior**
Consideremos la matriz triangular inferior:
$$
B=
\begin{pmatrix}
4 & 0 & 0 \\
-1 & 2 & 0 \\
5 & 3 & -6
\end{pmatrix}
$$

Como es triangular inferior:

$$
\det(B)=4\cdot2\cdot(-6)=-48.
$$

In [30]:
B = np.array([
    [4, 0, 0],
    [-1, 2, 0],
    [5, 3, -6]
], dtype=float)
             
# Determinante directo por producto de la diagonal
det_diagonal_B = np.prod(np.diag(B))

# Comprobación con NumPy
det_numpy_B = np.linalg.det(B)

print("Matriz B:")
print(B)
print("\nProducto de la diagonal:", det_diagonal_B)
print("Determinante con numpy.linalg.det", det_numpy_B)

Matriz B:
[[ 4.  0.  0.]
 [-1.  2.  0.]
 [ 5.  3. -6.]]

Producto de la diagonal: -48.0
Determinante con numpy.linalg.det -47.999999999999986


### c) Efecto de las operaciones elementales sobre el determinante

*Respuesta teórica:* TODO
- Intercambiar dos filas (o columnas): ...
- Sumar a una fila otra fila multiplicada por un escalar $\alpha$: ...

### d) Eliminación de Gauss con pivoteo parcial

Implementar el escalonado con pivoteo parcial (devolviendo también el nº de intercambios).

In [ ]:
def escalonar(A):
    # TODO: eliminación gaussiana con pivoteo parcial
    pass

### e) Determinante mediante eliminación gaussiana

Implementar `determinante_gauss` apoyándose en el escalonado anterior.

In [ ]:
def determinante_gauss(A):
    # TODO: (-1)**intercambios * producto de la diagonal de la matriz escalonada
    pass

In [ ]:
# TODO: comprobar que recursivo, gauss y numpy coinciden

### f) Coste computacional de ambos métodos

*Respuesta teórica:* TODO (complejidad del recursivo y de Gauss con pivoteo parcial).

### g) Comparativa de tiempos

Generar matrices aleatorias para $2\le n\le 10$, cronometrar las tres variantes y comentar.

In [ ]:
# TODO: bucle de tiempos para determinante_recursivo, determinante_gauss y np.linalg.det
#       construir tabla comparativa (pandas) y graficar

*Interpretación de los resultados:* TODO

## Ejercicio 2. Descenso de gradiente

### a) Implementación para funciones de $n$ variables

Programar `descenso_gradiente(grad_f, x0, gamma, tol, maxit)` que devuelva la aproximación de $x$
con $\nabla f(x)\approx 0$. Criterio de parada: $\lVert\nabla f(x)\rVert_2 < $ tol.

In [33]:
def descenso_gradiente(grad_f, x0, gamma, tol=1e-12, maxit=100000):
    """
    Método de descenso de gradiente para funciones f: R^n -> R.
    """
    x = np.array(x0, dtype=float)

    for it in range(int(maxit)):
        grad = np.array(grad_f(x), dtype=float)

        if np.linalg.norm(grad) < tol:
            return x, it

        x = x - gamma * grad

        # Control básico para evitar overflow si diverge
        if not np.all(np.isfinite(x)) or np.linalg.norm(x) > 1e100:
            return x, it + 1

    return x, int(maxit)

### b) Función $f(x)=3x^4+4x^3-12x^2+7$

*Estudio analítico previo:* TODO (puntos críticos y clasificación).

In [ ]:
def f(x):
    # TODO
    pass

def grad_f(x):
    # TODO
    pass

#### i) $x_0=3$, $\gamma=0.001$, tol=1e-12, maxit=1e5

In [ ]:
# TODO

#### ii) $x_0=3$, $\gamma=0.01$, tol=1e-12, maxit=1e5

In [ ]:
# TODO

#### iii) Comparación de (i) y (ii) e influencia de $\gamma$

*Interpretación:* TODO

#### iv) $x_0=3$, $\gamma=0.1$, tol=1e-12, maxit=1e5

In [ ]:
# TODO

*Interpretación:* TODO

#### v) $x_0=0$, $\gamma=0.001$, tol=1e-12, maxit=1e5

In [ ]:
# TODO

*Interpretación:* TODO

### c) Función $g(x,y)=x^2+y^3+3xy+1$

In [ ]:
def g(v):
    # TODO
    pass

def grad_g(v):
    # TODO
    pass

#### i) $x_0=(-1,1)$, $\gamma=0.01$

In [ ]:
# TODO

#### ii) $x_0=(0,0)$, $\gamma=0.01$

In [ ]:
# TODO

#### iii) Estudio analítico de $g$ y contraste

*Respuesta:* TODO (puntos críticos, hessiana, clasificación, contraste con i y ii).