# Ejercicios Evaluables
**02MIAR | Matemáticas para la Inteligencia Artificial**

**Miembros del Grupo 20:**
- Jorge Ramilo Plata
- Carlos Jurado Zalaya
- Ricardo Germes Serrano
- Ana María Cochiorca Dragomir

## Ejercicio nº1: Determinante de una matriz

Tal y como ya hemos visto en clase, la variedad de herramientas proporcionadas por el álgebra lineal son cruciales para desarrollar y fundamentar las bases de una variedad de técnicas relacionadas con el aprendizaje automático. Con ella, podemos describir el proceso de propagación hacia adelante en una red neuronal, identificar mínimos locales en funciones multivariables (crucial para el proceso de retropropagación) o la descripción y empleo de métodos de reducción de la dimensionalidad, como el análisis de componentes principales (PCA), entre muchas otras aplicaciones.
    
Cuando trabajamos en la práctica dentro de este ámbito, la cantidad de datos que manejamos puede ser muy grande, por lo que es especialmente importante emplear algoritmos eficientes y optimizados para reducir el coste computacional en la medida de lo posible. Por todo ello, el objetivo de este ejercicio es el de ilustrar las diferentes alternativas que pueden existir para realizar un proceso relacionado con el álgebra lineal y el impacto que puede tener cada variante en términos del coste computacional del mismo. En este caso en particular, y a modo de ilustración, nos centraremos en el cálculo del determinante de una matriz.

a) [1 punto] Implementa una función, determinante recursivo, que obtenga el determinante de una matriz cuadrada utilizando la definición recursiva de Laplace.

b) [0.5 puntos] Si A es una matriz cuadrada n×n y triangular (superior o inferior, es decir, con entradas nulas por debajo o por encima de la diagonal, respectivamente), ¿existe alguna forma de calcular de forma directa y sencilla su determinante? Justifíquese la respuesta.

c) [0.5 puntos] Determínese de forma justificada cómo alteran el determinante de una matriz n × n las dos operaciones elementales siguientes:
- Intercambiar una fila (o columna) por otra fila (o columna).
- Sumar a una fila (o columna) otra fila (o columna) multiplicada por un escalar α.
    
d) [1 punto] Investiga sobre el método de eliminación de Gauss con pivoteo parcial e impleméntalo para escalonar una matriz (es decir, convertirla en una matriz triangular inferior) a partir de las operaciones elementales descritas en el apartado anterior.

e) [0.5 puntos] ¿Cómo se podría calcular el determinante de una matriz haciendo beneficio de la estrategia anterior y del efecto de aplicar las operaciones elementales pertinentes? Implementa una nueva función, determinante gauss, que calcule el determinante de una matriz utilizando eliminación gaussiana.

f ) [0.5 puntos] Obtén la complejidad computacional asociada al cálculo del determinante con la definición recursiva y con el método de eliminación de Gauss con pivoteo parcial.

g) [1 punto] Utilizando numpy.random.rand, genera matrices cuadradas aleatorias de la forma An ∈ Rn×n, para 2 ≤ n ≤ 10, y confecciona una tabla comparativa del tiempo de ejecución asociado a cada una de las variantes siguientes, interpretando los resultados:
- Utilizando determinante recursivo.
- Empleando determinante gauss.
- Haciendo uso de la función preprogramada numpy.linalg.det.


# 1. Determinante de una matriz

El determinante de una matriz cuadrada puede calcularse mediante la definición recursiva de Laplace. Si $A \in \mathbb{R}^{n \times n}$, entonces:

$$
\det(A)=\sum_{j=1}^{n}(-1)^{1+j}a_{1j}\det(A_{1j}),
$$

donde $A_{1j}$ es la matriz resultante de eliminar la fila 1 y la columna $j$.

## 1a. Implementa una función `determinante_recurivo` 
La función debe calcular el determinante de una matriz cuadrada usando la expansión de Laplace.

**Pasos:**

1. Si la matriz es $1\times1$, devolver su único elemento.
2. Si la matriz es $2\times2$, usar directamente $ad-bc$.
3. Para matrices mayores, recorrer la primera fila.
4. Para cada elemento, construir la submatriz eliminando la fila 0 y la columna correspondiente.
5. Acumular el cofactor correspondiente.

In [15]:
def determinante_recursivo(A):
    """
    Calcula el determinante de una matriz cuadrada A usando
    la definición recursiva de Laplece por la pimrera fila.
    """
    n = len(A)

    # Caso base 1x1:
    if n == 1:
        return A[0][0]

    # Caso base 2x2:
    if n == 2:
        return A[0][0] * A[1][1] - A[0][1] * A[1][0]

    det = 0.0
    for j in range(n):
        submatriz = [fila[:j] + fila[j+1:] for fila in A[1:]]
        cofactor = ((-1) ** j) * A[0][J] * determinante_recursivo(submatriz)
        det += cofactor

    return det

# Prueba:
A = [[1, 2], [3, 4]]
print("det(A) =", determinante_recursivo(A))

det(A) = -2


## 1b. Determinante de una matriz triangular

Sí. Si $A$ es una matriz cuadrada triangular, ya sea superior o inferior, su determinante se calcula multiplicando los elementos de la diagonal principal:

$$
\det(A)=a_{11}a_{22}\cdots a_{nn}=\prod_{i=1}^{n}a_{ii}.
$$

## JUSTIFICACIÓN.

**PRIMERO:**
Partimos de una matriz cuadrada $n \times n$, donde: $$ A \in \mathbb{R}^{n \times n}$$ 
Esto signfica que $A$ tiene $n$ filas y $n$ columnas.


**SEGUNDO:**
En una matriz triangular superior, todos los elementos por debajo de la diagonal principal son cero. Por ejemplo:

$$
A=
\begin{pmatrix}
a_{11} & a_{12} & a_{13} & \cdots & a_{1n} \\
0 & a_{22} & a_{23} & \cdots & a_{2n} \\
0 & 0 & a_{33} & \cdots & a_{3n} \\
\vdots & \vdots & \vdots & \ddots & \vdots \\
0 & 0 & 0 & \cdots & a_{nn}
\end{pmatrix}
$$

Los elementos de la diagonal principal son:

$$
a_{11}, a_{22}, a_{33}, \ldots, a_{nn}.
$$


**TERCERO:**
Si usamos la definición recursiva del determinate, según la definición de Laplace, el determinante de una matriz cuadrada se puede calcular como:
$$
\det(A)=\sum_{j=1}^{n}(-1)^{1+j}a_{1j}\det(A_{1j}),
$$
Donde: $A_{1j}$ es la submatriz que se obtiene al eliminar la fila 1 y la columna $j$.


**CUARTO:**
Si la matriz es triangular, al ir calculando determinantes de submatrices, estas submatrices mantienen la estructura triangular, es decir: como la matriz tiene ceros a un lado de la diagonal, al calcular su determinante solo van quedando los números de la diagonal principal. Por eso no hace falta hacer un cálculo largo, basta con multiplicar esos números.


**QUINTO:**
Justificación con una matriz triangular superior.

Partimos de que tenemos una matriz: 
$$
A=
\begin{pmatrix}
a_{11} & * & * & \cdots & * \\
0 & a_{22} & * & \cdots & * \\
0 & 0 & a_{33} & \cdots & * \\
\vdots & \vdots & \vdots & \ddots & \vdots \\
0 & 0 & 0 & \cdots & a_{nn}
\end{pmatrix}
$$

Al aplicar la expansión de Laplace, el cálculo se reduce a:

$$
\det(A)=a_{11}\det(A_{11}).
$$
La submatriz $A_{11}$ también es triangular superior:

$$
A_{11}=
\begin{pmatrix}
a_{22} & * & \cdots & * \\
0 & a_{33} & \cdots & * \\
\vdots & \vdots & \ddots & \vdots \\
0 & 0 & \cdots & a_{nn}
\end{pmatrix}
$$

Por lo tanto:

$$
\det(A_{11})=a_{22}\det(A_{22}).
$$

Sustituyendo:

$$
\det(A)=a_{11}a_{22}\det(A_{22}).
$$

Repitiendo el mismo razonamiento:

$$
\det(A)=a_{11}a_{22}a_{33}\cdots a_{nn}.
$$


**SEXTO:**
Justificación con una matriz triangular inferior.

En este caso la matriz triángular inferior tiene ceros por encima de la diagonal principal, como por ejemplo:

$$
A=
\begin{pmatrix}
a_{11} & 0 & 0 & \cdots & 0 \\
a_{21} & a_{22} & 0 & \cdots & 0 \\
a_{31} & a_{32} & a_{33} & \cdots & 0 \\
\vdots & \vdots & \vdots & \ddots & \vdots \\
a_{n1} & a_{n2} & a_{n3} & \cdots & a_{nn}
\end{pmatrix}
$$

como en el caso de la matriz triangular superior al hacerse del mismo modemos, también obtenemos que:

$$
\det(A)=a_{11}a_{22}\cdots a_{nn}.
$$


### Ejercicios de Ejemplo



**1) Ejercicio con matriz triángulo Superior**

Consideremos la matriz triangular superior:

$$
A=
\begin{pmatrix}
2 & 5 & -1 \\
0 & 3 & 4 \\
0 & 0 & -2
\end{pmatrix}
$$

Como es triangular superior:

$$
\det(A)=2\cdot3\cdot(-2)=-12.
$$

In [28]:
import numpy as np

A = np.array([
    [2, 5, -1],
    [0, 3, 4],
    [0, 0, -2]
], dtype=float)
             
# Determinante directo por producto de la diagonal
det_diagonal = np.prod(np.diag(A))

# Comprobación con NumPy
det_numpy = np.linalg.det(A)

print("Matriz A:")
print(A)
print("\nProducto de la diagonal:", det_diagonal)
print("Determinante con numpy.linalg.det", det_numpy)

Matriz A:
[[ 2.  5. -1.]
 [ 0.  3.  4.]
 [ 0.  0. -2.]]

Producto de la diagonal: -12.0
Determinante con numpy.linalg.det -12.0


**2) Ejercicio con matriz triángulo Inferior**
Consideremos la matriz triangular inferior:
$$
B=
\begin{pmatrix}
4 & 0 & 0 \\
-1 & 2 & 0 \\
5 & 3 & -6
\end{pmatrix}
$$

Como es triangular inferior:

$$
\det(B)=4\cdot2\cdot(-6)=-48.
$$

In [30]:
B = np.array([
    [4, 0, 0],
    [-1, 2, 0],
    [5, 3, -6]
], dtype=float)
             
# Determinante directo por producto de la diagonal
det_diagonal_B = np.prod(np.diag(B))

# Comprobación con NumPy
det_numpy_B = np.linalg.det(B)

print("Matriz B:")
print(B)
print("\nProducto de la diagonal:", det_diagonal_B)
print("Determinante con numpy.linalg.det", det_numpy_B)

Matriz B:
[[ 4.  0.  0.]
 [-1.  2.  0.]
 [ 5.  3. -6.]]

Producto de la diagonal: -48.0
Determinante con numpy.linalg.det -47.999999999999986


## 1c. Efecto de operaciones elementales sobre el determinante.


## 1d. Eliminación de Gauss con pivoteo parcial

## 1e. Determinante mediante eliminación gaussiana

## 1f. Complejidad computacional

## 1g. Tabla comparativa de tiempos

## Ejercicio nº2: Descenso de gradiente

En este ejercicio trabajaremos con el método de descenso de gradiente, el cual constituye otra herramienta crucial, en esta ocasión de la rama del cálculo, para el proceso de retropropagación asociado al entrenamiento de una red neuronal.
    
**a) [1 punto] Prográmese en Python el método de descenso de gradiente para funciones de n variables. La función deberá tener como parámetros de entradas:**
- El gradiente de la función que se desea minimizar ∇f (puede venir dada como otra función previamente implementada, grad f, con entrada un vector, representando
el punto donde se quiere calcular el gradiente, y salida otro vector, representando el gradiente de f en dicho punto).
- Un valor inicial $ x_0 ∈ Rn $ (almacenado en un vector de n componentes).
- El ratio de aprendizaje γ (que se asume constante para cada iteración).
- Un parámetro de tolerancia tol (con el que finalizar el proceso cuando ∥∇f(x)∥2 < tol).
- Un número máximo de iteraciones maxit (con el fin de evitar ejecuciones indefinidas en caso de divergencia o convergencia muy lenta).

La salida de la función deberá ser la aproximación del x que cumple f′(x) ≈ 0, correspondiente a la última iteración realizada en el método.


**b) Sea la función f : R → R dada por
$$ f(x) = 3x^4 + 4x^3 − 12x^2 + 7. $$**

- i. [0.5 puntos] Aplica el método sobre f(x) con $$ x_0 = 3,  \qquad γ = 0.001,  \qquad tol=1e-12,  \qquad  maxit=1e5. $$

- ii. [0.5 puntos] Aplica de nuevo el método sobre f(x) con $$ x_0 = 3,  \qquad γ = 0.01,  \qquad tol=1e-12,  \qquad maxit=1e5.$$

- iii. [0.5 puntos] Contrasta e interpreta los dos resultados obtenidos en los apartados anteriores y compáralos con los mínimos locales obtenidos analíticamente. ¿Qué influencia puede llegar a tener la elección del ratio de aprendizaje γ?

- iv. [0.5 puntos] Aplica nuevamente el método sobre f(x) con $ x_0 = 3, \qquad  γ = 0.1, \qquad  tol=1e-12, \qquad  maxit=1e5. $ Interpreta el resultado. 

- v. [0.5 puntos] Finalmente, aplica el método sobre f(x) con $ x_0 = 0,  \qquad γ = 0.001,  \qquad tol=1e-12, \qquad maxit=1e5. $ Interpreta el resultado y compáralo con el estudio analítico de f. ¿Se trata de un resultado deseable? ¿Por qué? ¿A qué se debe este fenómeno?


**c) Sea la función g : R2 → R dada por $$ g(x, y) = x^2 + y^3 + 3xy + 1. $$**
- i [0.5 puntos] Aplíquese el método sobre g(x, y) con $$ x_0 = (−1, 1), \qquad γ = 0.01, \qquad tol=1e-12, \qquad maxit=1e5.$$

- ii [0.5 puntos] ¿Qué ocurre si ahora partimos de $ x_0 = (0, 0)$? ¿Se obtiene un resultado deseable?

- iii [0.5 puntos] Realícese el estudio analítico de la función y utilícese para explicar y contrastar los resultados obtenidos en los dos apartados anteriores.

## 2a. Programación del descenso del gradiente para funciones de n variables

La función recibirá:

- `grad_f`: función que calcula el gradiente.
- `x0`: punto inicial.
- `gamma`: ratio de aprendizaje constante.
- `tol`: tolerancia para parar cuando $\|\nabla f(x)\|_2 < tol$.
- `maxit`: número máximo de iteraciones.

La salida será la última aproximación calculada y el número de iteraciones realizadas.

In [33]:
def descenso_gradiente(grad_f, x0, gamma, tol=1e-12, maxit=100000):
    """
    Método de descenso de gradiente para funciones f: R^n -> R.
    """
    x = np.array(x0, dtype=float)

    for it in range(int(maxit)):
        grad = np.array(grad_f(x), dtype=float)

        if np.linalg.norm(grad) < tol:
            return x, it

        x = x - gamma * grad

        # Control básico para evitar overflow si diverge
        if not np.all(np.isfinite(x)) or np.linalg.norm(x) > 1e100:
            return x, it + 1

    return x, int(maxit)

## 2b. Funciones de una variable.

## 2c. Funciones de dos variables.